import type { NextPage } from "next";
import dynamic from "next/dynamic";
const TableComponent = dynamic(() => import("../components/Table"), {
  ssr: false,
});
import { Input, Stack } from "@chakra-ui/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import data from "../data/activities.json";
import React, { useState } from "react";
import useStore from "../store";
import SelectedActivities from "../components/SelectedActivities";


const Home: NextPage = () => {
  const [activities, setActivities] = useState(data.data.allActivities);
  const { selectedActivities } = useStore();

  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    const search = e.target.value;
    const searchText = search.toLowerCase();
    const filteredActivities = data.data.allActivities.filter(
      (activity) =>
        activity.name.toLowerCase().includes(searchText.toLowerCase()) ||
        activity.description.toLowerCase().includes(searchText.toLowerCase()) ||
        activity.sector.name.toLowerCase().includes(searchText.toLowerCase()) ||
        activity.reference.toLowerCase().includes(searchText.toLowerCase()) ||
        activity.naceCodes
          .map((n) => n.code.toLowerCase())
          .join("")
          .includes(searchText)
    );
    setActivities(filteredActivities);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>EU Company Activities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.headerContainer}> 
        <Input
          pr='7.5rem'
          placeholder="Search by name, sector, or nace code"
          onChange={handleSearch}
        />
        <SelectedActivities/>
        </div> 
        <TableComponent activities={activities} />
       
      </main>
    </div>
  );
};

export default Home;
